[extend]
useDefault = true

[allowlist]
    paths = [
    '''dist''',
    '''.automation/test''',
    '''megalinter-reports''',
    '''.github/linters''',
    '''node_modules''',
    '''.mypy_cache''',
    '''(.*?)gitleaks\.toml$''',
    '''(.*?)(png|jpg|gif|doc|docx|pdf|bin|xls|pyc|zip)$''',
    '''(go.mod|go.sum)$''']
